### ISSUE TITLE
PanelSettings?

### ISSUE THREAD

**Issue by vvoovv** [JeremyBYU/bpyproj#10]
What is role of the class PanelSettings? Is it for GUI testing?

blender-osm also has the class with exactly the same name. So there is a name fight between them. The one parsed later wins.
I'll rename mine.

**Comment by JeremyBYU** [comment]
Yeah it was just for testing. I didn't have your plugin installed on all my
other vms. I was thinking I would remove it once everything is done being
tested.  Unless you think it might be necessary.

**Comment by vvoovv** [comment]
The panel was deleted in 832ca9b
