### ISSUE TITLE
SRID from a list?

### ISSUE THREAD

**Issue by vvoovv** [JeremyBYU/bpyproj#12]
How about selecting SRID from a list?

![image](https://user-images.githubusercontent.com/613295/39874588-e8101e84-5476-11e8-9a90-df69a872efea.png)

**Comment by JeremyBYU** [comment]
There are a lot of EPSG codes that are supported by pyproj.  They are all listed [here](https://github.com/jswhit/pyproj/blob/master/lib/pyproj/data/epsg), about 5500. There are also projections supported for ESRI as well [here](https://github.com/jswhit/pyproj/blob/master/lib/pyproj/data/esri), about 3000.  

We could read in these files to construct the the dropdown/selection box. However do you think that just too many options for the user, and maybe to much for the GUI to handle?

**Comment by vvoovv** [comment]
It seems that a Blender list doesn't have a search box. If so, it isn't feasible.
