### ISSUE TITLE
imgs aren't used by the code

### ISSUE THREAD

**Issue by vvoovv** [JeremyBYU/bpyproj#13]
I suggest to move the directory _imgs_ to an orphan branch:
`git checkout --orphan images`
OR to the wiki repo:
`git clone git@github.com:JeremyBYU/bpyproj.wiki.git`

**Comment by JeremyBYU** [comment]
The `README.md` is also not used by the code.  I think having the documentation as part of the download is a good thing, which includes the 2 pictures. The `README.md` and pictures take up 18 KB, which is a small fraction of the total download. 

I think in general a Wiki is a good idea, but I thought it was a little overkill for this plugin. If you feel strongly about it however, I can make a wiki and move the picture and documentation over to it.

**Comment by vvoovv** [comment]
It's up to you.
However I'm going to create a wiki page "bpyproj for addon developers"

**Comment by JeremyBYU** [comment]
Okay sounds good.
