### ISSUE TITLE
Placing additional georeferenced objects on the map

### ISSUE THREAD

**Issue by stolensharingan** [JeremyBYU/bpyproj#20]
Hi there, 

Thanks for the brilliant work!
I have followed your tutorial, and it has worked really well for my project.

The next step for me is to place additional georeferenced objects (e.g., place objects at geolocations, and have the drone fly to them one after another) in the environment.

Could you suggest a way I can place the additional objects in the simulation corresponding to the custom geolocations?
I feel like I have all the pieces (thanks to you), but I'm having a bit of trouble joining them.

Any help would be appreciated!

**Comment by vvoovv** [comment]
This is a repo with the source of the bpyproj addon.

It looks like your question is related to the Blender-OSM addon. If so, please post your question at https://github.com/vvoovv/blender-osm/issues

Thank you for your understanding!

**Comment by stolensharingan** [comment]
Many apologies,
I thought this would be the right place to ask since I'm looking to project the real-world coordinates into Unreal engine, and place additional objects there.

I will close this, and open another one in the correct repo.
Thanks once again!
