### ISSUE TITLE
PyprojProperties.proj_params property not found

### ISSUE THREAD

**Issue by ibaris** [JeremyBYU/bpyproj#21]
I receive the following message on start up:
```
\Blender\3.4\scripts\addons\bpyproj\__init__.py:97 
rna_uiItemR: property not found: PyprojProperties.proj_params
```

I already installed pyproj. How can I solve this problem?

**Comment by vvoovv** [comment]
Unfortunately bpyproj works only in Blender 2.8x. See also [here](https://github.com/vvoovv/blender-osm/wiki/Documentation#custom-map-projections).
