### ISSUE TITLE
moving "install dependencies" button to the addon settings?

### ISSUE THREAD

**Issue by vvoovv** [JeremyBYU/bpyproj#3]
What do you think about moving the "install dependencies" button to the addon settings?

**Comment by JeremyBYU** [comment]
Yep I got it. I didn't know it was possible before. Only concern are the
messages that pop up might be obscured by the preference pop-up window. Not
sure of that yet.

I'll try it out.

**Comment by JeremyBYU** [comment]
Okay just finished this. Looks better now! Good idea!

**Comment by JeremyBYU** [comment]
Removed the button.
