### ISSUE TITLE
untrack .vscode

### ISSUE THREAD

**Issue by vvoovv** [JeremyBYU/bpyproj#4]
Please add it to .gitignore_global or .gitignore

**Comment by JeremyBYU** [comment]
Done.

**Comment by vvoovv** [comment]
Could you add .gitignore itself to .gitignore?
Not sure if it works.

I personally add the stuff to be ignored to .gitignore_global

**Comment by vvoovv** [comment]
.gignore is still there.
Maybe forgot to commit or push?

**Comment by JeremyBYU** [comment]
Oh I totally read your question wrong!  You want to add .gitinore to the actual .gitignore file.  You want not  just .vscode to be untracked, you *also* want .gitignore to be untracked. Is that correct?

If so, why is that. I *always* have my .gitignore in repo, to ensure that that common build artificats are not accidentally committed to the repository (see pythons bytode in `__pycache__` folder and **many** others). Here's a [link](https://stackoverflow.com/questions/5765645/should-you-commit-gitignore-into-the-git-repos) that explains it better.

**Comment by vvoovv** [comment]
ok
