### ISSUE TITLE
PROJ.4 parameters support

### ISSUE THREAD

**Issue by vvoovv** [JeremyBYU/bpyproj#5]
Are you going to support an arbitrary map projection defined by a string of PROJ.4 parameters:
http://proj4.org/parameters.html

**Comment by JeremyBYU** [comment]
Yes, just added support for this.

**Comment by vvoovv** [comment]
We have both SRID and PROJ.4 parameters in GUI at once.
As far as I understand a projection is defined either by SRID or be PROJ.4 parameters.
Correct?

If yes, then a more complex GUI with a switch between SRID and PROJ.4 is required.

**Comment by JeremyBYU** [comment]
Yeah, was being a bit lazy and just added another field which took preference if not an empty string. I agree a better GUI is needed and I just finished adding it.  Looks way better now, thanks.
