### ISSUE TITLE
testing bpyproj

### ISSUE THREAD

**Issue by vvoovv** [JeremyBYU/bpyproj#7]
binaries have been successfully copied for me without running Blender under administrator (I use zip-distribution of Blender instead of installer).

But then it didn't work

I called `import pyproj` in the Python Console of Blender and got:
```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "D:\software\blender-2.79b-windows64\2.79\python\lib\site-packages\pyproj\__init__.py", line 51, in <module>
    from pyproj import _proj
ImportError: cannot import name '_proj'
```

Maybe something else is missing?

**Comment by JeremyBYU** [comment]
Yes, you don't need administrator if you are *not* installed in `C:\Program Files`. However I would wager must people just click the installer.

 Hmm...can you tell me what OS and architecture you are using.  Its clearly copied *something* correctly. Right now I only have x64, python 3.5 for bundled for Windows.

**Comment by JeremyBYU** [comment]
Ha I think I just figured out what it was! My .gitignore file needs a special rule to allow build artifacts for the binary folder. 

Just fixed and pushed update.

**Comment by JeremyBYU** [comment]
As a note, it does look like most windows users (80% use the MSI installer). However something a little disconcerting is that about 20% of the user still use Win32. Maybe I should bundle that dependency too....


![image](https://user-images.githubusercontent.com/6628085/39526798-e13e106e-4ded-11e8-958d-9d7fc8521cfd.png)

**Comment by vvoovv** [comment]
all dependencites seem to be there now
